from typing import Any, Callable
from .core import Schema

class ConditionalRule:
    text: str
    def __init__(
        self,
        condition: Callable | str,
        rule: str,
        label: str = ...,
        else_rule: str | None = ...,
    ) -> None: ...
    def check(self, value: Any) -> tuple[bool, str]: ...

class DependentSchema(Schema):
    def __init__(
        self,
        fields: dict,
        dependencies: dict | None = ...,
    ) -> None: ...

class TransitionRule:
    field: str
    description: str
    def __init__(self, field: str, description: str, check: Callable) -> None: ...
    @staticmethod
    def immutable(field: str) -> "TransitionRule": ...
    @staticmethod
    def append_only(field: str) -> "TransitionRule": ...
    @staticmethod
    def monotone_increase(field: str) -> "TransitionRule": ...
    @staticmethod
    def allowed_transitions(field: str, transitions: dict) -> "TransitionRule": ...
    @staticmethod
    def no_delete(field: str) -> "TransitionRule": ...

def diff_validate(
    old: dict[str, Any],
    new: dict[str, Any],
    schema: Schema | None = ...,
    transition_rules: list[TransitionRule] | None = ...,
) -> dict[str, Any]: ...

class WatchedDict:
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def update(self, other: dict) -> None: ...
    def to_dict(self) -> dict: ...
    def history(self) -> list[tuple]: ...

def watch(
    data: dict,
    schema: Schema,
    on_violation: Callable | None = ...,
) -> WatchedDict: ...

def generate(rule: str, n: int = ...) -> Any: ...
def from_json_schema(json_schema: dict) -> Schema: ...
def to_json_schema(schema: Schema, title: str = ...) -> dict: ...
async def async_validate(value: Any, *rules: str) -> Any: ...
async def async_schema_validate(data: dict, schema: Schema) -> dict: ...
