from typing import Any, Callable

PATTERNS: list[tuple[Any, Callable]]

def pattern(regex: str, canonical: str = ...) -> Callable: ...
def compile_rule(text: str) -> Callable[[Any], tuple[bool, str]]: ...
def list_patterns() -> list[str]: ...
def _fuzzy_normalize(text: str) -> str: ...
def _levenshtein(a: str, b: str) -> int: ...
def _suggest_closest(text: str) -> str: ...
