from typing import Any, overload
from dataclasses import dataclass, field

class ValidationError(Exception):
    errors: dict[str, list[str]]
    def __init__(self, errors: dict[str, list[str]]) -> None: ...

@dataclass
class Rule:
    text: str
    optional: bool = ...
    def check(self, value: Any) -> tuple[bool, str]: ...

class Schema:
    _fields: dict[str, list[Rule]]
    def __init__(self, fields: dict[str, Rule | list[Rule]]) -> None: ...
    def validate(self, data: dict[str, Any], *, strict: bool = ...) -> dict[str, Any]: ...
    def is_valid(self, data: dict[str, Any]) -> bool: ...
    def errors(self, data: dict[str, Any]) -> dict[str, list[str]]: ...

def validate(value: Any, *rules: str | Rule) -> Any: ...
