from typing import Any
from dataclasses import dataclass, field
from .core import Schema, Rule

def explain(rule: str) -> str: ...
def suggest(value: Any, max_results: int = ...) -> list[str]: ...

@dataclass
class BatchReport:
    total: int
    valid: int
    invalid: int
    errors_by_row: dict[int, dict[str, list[str]]]
    @property
    def pass_rate(self) -> float: ...
    def summary(self) -> str: ...
    def to_csv(self) -> str: ...
    def invalid_rows(self) -> list[int]: ...

def batch_validate(
    data: list[dict],
    schema: Schema,
    *,
    stop_at: int | None = ...,
) -> BatchReport: ...

class SchemaBuilder:
    def learn(self, sample: dict | list) -> "SchemaBuilder": ...
    def build(self) -> Schema: ...
    def describe(self) -> str: ...

def validate_args(**rules: str | list[str]): ...
def add_i18n_rule(alias: str, canonical: str) -> None: ...
def list_i18n_aliases(lang: str | None = ...) -> dict[str, str]: ...
