from typing import Any, Callable

class Pipeline:
    def __init__(self, value: Any) -> None: ...
    def transform(self, fn: Callable[[Any], Any], label: str = ...) -> "Pipeline": ...
    def validate(self, rule: str) -> "Pipeline": ...
    def default(self, fallback: Any) -> "Pipeline": ...
    def strip(self) -> "Pipeline": ...
    def lower(self) -> "Pipeline": ...
    def upper(self) -> "Pipeline": ...
    def cast(self, target_type: type) -> "Pipeline": ...
    def clamp(self, lo: float, hi: float) -> "Pipeline": ...
    def is_valid(self) -> bool: ...
    def result(self) -> Any: ...
    def value(self) -> Any: ...
    def errors(self) -> list[str]: ...
    def trace(self) -> str: ...
