from typing import Any
from .core import Rule, Schema

class RuleSet:
    @classmethod
    def register(cls, name: str, rules: list[str], *, overwrite: bool = ...) -> None: ...
    @classmethod
    def get(cls, name: str) -> list[str]: ...
    @classmethod
    def schema_rules(cls, name: str) -> list[Rule]: ...
    @classmethod
    def validate(cls, value: Any, name: str) -> Any: ...
    @classmethod
    def is_valid(cls, value: Any, name: str) -> bool: ...
    @classmethod
    def list(cls) -> list[str]: ...
    @classmethod
    def describe(cls, name: str) -> str: ...
    @classmethod
    def extend(cls, name: str, extra_rules: list[str], new_name: str | None = ...) -> str: ...
