from typing import Any, Callable
from .core import Schema, Rule

class CustomRule:
    text: str
    optional: bool
    def __init__(
        self,
        fn: Callable,
        *,
        name: str = ...,
        error: str = ...,
        optional: bool = ...,
    ) -> None: ...
    def check(self, value: Any) -> tuple[bool, str]: ...

class RuleCache:
    def add(self, name: str, *rule_texts: str) -> "RuleCache": ...
    def check(self, name: str, value: Any) -> tuple[bool, list[str]]: ...
    def validate(self, name: str, value: Any) -> Any: ...
    def keys(self) -> list[str]: ...

def validate_file(
    path: str,
    schema: Schema,
    *,
    file_format: str = ...,
    encoding: str = ...,
    delimiter: str = ...,
    stop_at: int | None = ...,
) -> Any: ...

def report_html(
    data: list[dict] | dict,
    schema: Schema,
    *,
    title: str = ...,
    output_path: str | None = ...,
) -> str: ...

def debug_rule(rule_text: str, value: Any) -> str: ...
def profile(rule_text: str, value: Any, iterations: int = ...) -> dict: ...
def merge_schemas(*schemas: Schema, on_conflict: str = ...) -> Schema: ...
def optional(*rule_texts: str) -> list[Rule]: ...

class StrictSchema(Schema): ...
def strict_schema(fields: dict) -> StrictSchema: ...
def mask(data: dict, *sensitive_fields: str, replacement: str = ...) -> dict: ...
def assert_valid(value: Any, *rules: str, msg: str = ...) -> None: ...
def assert_invalid(value: Any, *rules: str, msg: str = ...) -> None: ...
def summarize_schema(schema: Schema, *, indent: int = ...) -> str: ...
