"""Tests for all 326 built-in validation patterns."""
import pytest
from livecheck import validate, ValidationError


def ok(value, rule):
    """Assert value passes rule."""
    validate(value, rule)


def fail(value, rule):
    """Assert value fails rule."""
    with pytest.raises(ValidationError):
        validate(value, rule)


# ── Numbers ───────────────────────────────────────────────────────────────────

class TestNumbers:
    def test_positive(self):        ok(1, "must be a positive number");  fail(-1, "must be a positive number")
    def test_negative(self):        ok(-1, "must be a negative number"); fail(1, "must be a negative number")
    def test_between(self):         ok(50, "must be between 1 and 100"); fail(0, "must be between 1 and 100")
    def test_gt(self):              ok(11, "must be greater than 10");   fail(10, "must be greater than 10")
    def test_lt(self):              ok(9, "must be less than 10");        fail(10, "must be less than 10")
    def test_gte(self):             ok(10, "must be greater than or equal to 10"); fail(9, "must be greater than or equal to 10")
    def test_lte(self):             ok(10, "must be less than or equal to 10");    fail(11, "must be less than or equal to 10")
    def test_integer(self):         ok(5, "must be an integer");         fail(5.5, "must be an integer")
    def test_float(self):           ok(5.5, "must be a float");          fail(5, "must be a float")
    def test_even(self):            ok(4, "must be even");               fail(3, "must be even")
    def test_odd(self):             ok(3, "must be odd");                fail(4, "must be odd")
    def test_multiple_of(self):     ok(9, "must be a multiple of 3");    fail(10, "must be a multiple of 3")
    def test_divisible_by(self):    ok(8, "must be divisible by 4");     fail(9, "must be divisible by 4")
    def test_prime(self):           ok(17, "must be a prime number");    fail(4, "must be a prime number")
    def test_perfect_square(self):  ok(16, "must be a perfect square");  fail(15, "must be a perfect square")
    def test_non_zero(self):        ok(1, "must be non-zero");           fail(0, "must be non-zero")
    def test_finite(self):          ok(1.0, "must be finite");           fail(float("inf"), "must be finite")
    def test_percentage(self):      ok(75.0, "must be a percentage");    fail(101, "must be a percentage")
    def test_equal(self):           ok(42.0, "must equal 42");           fail(43, "must equal 42")
    def test_power_of(self):        ok(8, "must be a power of 2");       fail(6, "must be a power of 2")
    def test_whole_number(self):    ok(3.0, "must be a whole number");   fail(3.1, "must be a whole number")
    def test_fibonacci(self):       ok(13, "must be a fibonacci number"); fail(14, "must be a fibonacci number")
    def test_happy(self):           ok(7, "must be a happy number");      fail(4, "must be a happy number")
    def test_perfect_num(self):     ok(6, "must be a perfect number");    fail(7, "must be a perfect number")
    def test_triangular(self):      ok(15, "must be a triangular number"); fail(14, "must be a triangular number")
    def test_narcissistic(self):    ok(153, "must be a narcissistic number"); fail(100, "must be a narcissistic number")
    def test_byte(self):            ok(200, "must be a byte value");      fail(256, "must be a byte value")
    def test_power_of_two(self):    ok(64, "must be a power of two");    fail(63, "must be a power of two")
    def test_natural(self):         ok(1, "must be a natural number");   fail(0, "must be a natural number")
    def test_probability(self):     ok(0.75, "must be a valid probability"); fail(1.5, "must be a valid probability")
    def test_latitude(self):        ok(48.8566, "must be a valid latitude"); fail(91.0, "must be a valid latitude")
    def test_longitude(self):       ok(2.3522, "must be a valid longitude"); fail(181.0, "must be a valid longitude")
    def test_unix_ts(self):         ok(1700000000, "must be a valid unix timestamp"); fail(-1, "must be a valid unix timestamp")
    def test_bool_not_number(self): fail(True, "must be a positive number")


# ── Strings ───────────────────────────────────────────────────────────────────

class TestStrings:
    def test_non_empty_string(self):    ok("hi", "must be a non-empty string");   fail("", "must be a non-empty string")
    def test_email(self):               ok("a@b.com", "must be a valid email");   fail("bad", "must be a valid email")
    def test_url(self):                 ok("https://example.com", "must be a valid url"); fail("example.com", "must be a valid url")
    def test_uuid(self):                ok("6ba7b810-9dad-11d1-80b4-00c04fd430c8", "must be a valid uuid"); fail("abc", "must be a valid uuid")
    def test_ip(self):                  ok("192.168.1.1", "must be a valid IP address"); fail("999.0.0.1", "must be a valid IP address")
    def test_ipv4(self):                ok("10.0.0.1", "must be a valid ipv4 address"); fail("::1", "must be a valid ipv4 address")
    def test_ipv6(self):                ok("::1", "must be a valid ipv6 address"); fail("192.168.1.1", "must be a valid ipv6 address")
    def test_slug(self):                ok("my-post", "must be a valid slug"); fail("My Post!", "must be a valid slug")
    def test_hex_color(self):           ok("#FF5733", "must be a valid hex color"); fail("red", "must be a valid hex color")
    def test_palindrome(self):          ok("racecar", "must be a palindrome"); fail("hello", "must be a palindrome")
    def test_trimmed(self):             ok("hello", "must be trimmed"); fail(" hello", "must be trimmed")
    def test_lowercase(self):           ok("hello", "must be lowercase"); fail("Hello", "must be lowercase")
    def test_uppercase(self):           ok("HELLO", "must be uppercase"); fail("Hello", "must be uppercase")
    def test_title_case(self):          ok("Hello World", "must be title case"); fail("hello world", "must be title case")
    def test_letters_only(self):        ok("hello", "must contain only letters"); fail("hello1", "must contain only letters")
    def test_digits_only(self):         ok("12345", "must contain only digits"); fail("12a", "must contain only digits")
    def test_alphanumeric(self):        ok("abc123", "must contain only alphanumeric characters"); fail("abc!", "must contain only alphanumeric characters")
    def test_ascii(self):               ok("hello", "must contain only ascii characters"); fail("héllo", "must contain only ascii characters")
    def test_starts_with(self):         ok("https://x.com", "must start with 'https'"); fail("http://x.com", "must start with 'https'")
    def test_ends_with(self):           ok("file.pdf", "must end with '.pdf'"); fail("file.txt", "must end with '.pdf'")
    def test_contains(self):            ok("hello world", "must contain 'world'"); fail("hello", "must contain 'world'")
    def test_not_contains(self):        ok("hello", "must not contain 'spam'"); fail("buy spam", "must not contain 'spam'")
    def test_regex(self):               ok("AB1234", "must match pattern '[A-Z]{2}[0-9]{4}'"); fail("ab1234", "must match pattern '[A-Z]{2}[0-9]{4}'")
    def test_one_of(self):              ok("admin", "must be one of admin, editor, viewer"); fail("god", "must be one of admin, editor, viewer")
    def test_min_len(self):             ok("hello", "must have length at least 3"); fail("hi", "must have length at least 3")
    def test_max_len(self):             ok("hi", "must have length at most 5"); fail("toolong!!", "must have length at most 5")
    def test_exact_len(self):           ok("abc", "must have length exactly 3"); fail("abcd", "must have length exactly 3")
    def test_json(self):                ok('{"a":1}', "must be valid json"); fail("{bad}", "must be valid json")
    def test_base64(self):              ok("aGVsbG8=", "must be valid base64"); fail("!@#$", "must be valid base64")
    def test_password(self):            ok("Secure@123", "must be a valid password"); fail("weak", "must be a valid password")
    def test_strong_password(self):     ok("MyStr0ng!Pass", "must be a valid strong password"); fail("Password1!", "must be a valid strong password")
    def test_phone(self):               ok("+33612345678", "must be a valid phone number"); fail("abc", "must be a valid phone number")
    def test_credit_card(self):         ok("4532015112830366", "must be a valid credit card number"); fail("1234567890", "must be a valid credit card number")
    def test_date(self):                ok("2024-01-15", "must be a valid date"); fail("not-a-date", "must be a valid date")
    def test_time(self):                ok("14:30", "must be a valid time"); fail("25:00", "must be a valid time")
    def test_datetime_str(self):        ok("2024-01-15 10:30:00", "must be a valid datetime"); fail("tomorrow", "must be a valid datetime")
    def test_semver(self):              ok("1.2.3", "must be a valid semver"); fail("1.2", "must be a valid semver")
    def test_mac(self):                 ok("AA:BB:CC:DD:EE:FF", "must be a valid mac address"); fail("AABBCCDDEE", "must be a valid mac address")
    def test_hostname(self):            ok("api.example.com", "must be a valid hostname"); fail("-bad.host", "must be a valid hostname")
    def test_domain(self):              ok("example.com", "must be a valid domain name"); fail("not a domain", "must be a valid domain name")
    def test_jwt(self):                 ok("aaa.bbb.ccc", "must be a valid jwt token"); fail("notjwt", "must be a valid jwt token")
    def test_md5(self):                 ok("d41d8cd98f00b204e9800998ecf8427e", "must be a valid md5 hash"); fail("short", "must be a valid md5 hash")
    def test_sha256(self):              ok("a" * 64, "must be a valid sha256 hash"); fail("short", "must be a valid sha256 hash")
    def test_username(self):            ok("alice_42", "must be a valid username"); fail("a!", "must be a valid username")
    def test_slug_2(self):              ok("hello-world", "must be a valid slug"); fail("Hello World", "must be a valid slug")
    def test_camelcase(self):           ok("myVariable", "must be camelCase string"); fail("MyVariable", "must be camelCase string")
    def test_pascalcase(self):          ok("MyClass", "must be PascalCase string"); fail("myClass", "must be PascalCase string")
    def test_snakecase(self):           ok("my_var", "must be snake_case string"); fail("myVar", "must be snake_case string")
    def test_kebabcase(self):           ok("my-var", "must be kebab-case string"); fail("my_var", "must be kebab-case string")
    def test_screaming_snake(self):     ok("MY_CONST", "must be SCREAMING_SNAKE_CASE string"); fail("my_const", "must be SCREAMING_SNAKE_CASE string")
    def test_semantic_commit(self):     ok("feat: add login", "must be a valid semantic commit message"); fail("added thing", "must be a valid semantic commit message")
    def test_otp(self):                 ok("123456", "must be a valid otp code"); fail("12345", "must be a valid otp code")
    def test_totp(self):                ok("987654", "must be a valid totp code"); fail("1234567", "must be a valid totp code")
    def test_no_sql_injection(self):    ok("hello world", "must not contain sql injection"); fail("SELECT * FROM users", "must not contain sql injection")
    def test_no_xss(self):              ok("hello world", "must not contain xss"); fail("<script>alert(1)</script>", "must not contain xss")
    def test_currency_code(self):       ok("EUR", "must be a valid currency code"); fail("XYZ", "must be a valid currency code")
    def test_country_code(self):        ok("FR", "must be a valid country code"); fail("XX", "must be a valid country code")
    def test_language_code(self):       ok("fr", "must be a valid language code"); fail("xx", "must be a valid language code")
    def test_mime_type(self):           ok("image/jpeg", "must be a valid mime type"); fail("jpeg", "must be a valid mime type")
    def test_locale(self):              ok("fr_FR", "must be a valid locale"); fail("fr-FR", "must be a valid locale")
    def test_log_level(self):           ok("INFO", "must be a valid log level"); fail("VERBOSE", "must be a valid log level")
    def test_http_status(self):         ok(200, "must be a valid http status code"); fail(99, "must be a valid http status code")
    def test_http_method(self):         ok("GET", "must be a valid http method"); fail("FETCH", "must be a valid http method")
    def test_port(self):                ok(8080, "must be a valid port number"); fail(99999, "must be a valid port number")
    def test_isbn(self):                ok("978-3-16-148410-0", "must be a valid isbn"); fail("123", "must be a valid isbn")
    def test_iban(self):                ok("FR76AABBCCC", "must be a valid iban"); fail("123", "must be a valid iban")
    def test_pypi_name(self):           ok("livecheck", "must be a valid pypi package name"); fail("My Package!", "must be a valid pypi package name")
    def test_git_hash(self):            ok("abc1234", "must be a valid git commit hash"); fail("xyz!", "must be a valid git commit hash")
    def test_docker_image(self):        ok("nginx:latest", "must be a valid docker image name"); fail("NGINX", "must be a valid docker image name")
    def test_env_var(self):             ok("MY_VAR", "must be a valid env var name"); fail("my-var", "must be a valid env var name")
    def test_python_id(self):           ok("my_var", "must be a valid python identifier"); fail("1bad", "must be a valid python identifier")
    def test_hashtag(self):             ok("#python", "must be a valid hashtag"); fail("python", "must be a valid hashtag")
    def test_iso8601(self):             ok("2024-01-15T10:30:00Z", "must be an iso 8601 date string"); fail("15/01/2024", "must be an iso 8601 date string")
    def test_github_url(self):          ok("https://github.com/user/repo", "must be a valid github repo url"); fail("https://gitlab.com/user/repo", "must be a valid github repo url")
    def test_zip_code(self):            ok("90210", "must be a valid zip code"); fail("9021", "must be a valid zip code")
    def test_uk_postcode(self):         ok("SW1A 1AA", "must be a valid uk postcode"); fail("12345", "must be a valid uk postcode")
    def test_us_state(self):            ok("CA", "must be a valid us state code"); fail("XX", "must be a valid us state code")
    def test_blood_type(self):          ok("AB+", "must be a valid blood type"); fail("C+", "must be a valid blood type")
    def test_blood_pressure(self):      ok("120/80", "must be a valid blood pressure"); fail("300/200", "must be a valid blood pressure")
    def test_icd10(self):               ok("A01.1", "must be a valid icd-10 code"); fail("XYZ", "must be a valid icd-10 code")
    def test_sku(self):                 ok("SKU-001", "must be a valid sku"); fail("s k u", "must be a valid sku")
    def test_no_whitespace(self):       ok("nospace", "must have no whitespace"); fail("has space", "must have no whitespace")
    def test_no_consecutive_spaces(self): ok("one space", "must not have consecutive spaces"); fail("two  spaces", "must not have consecutive spaces")
    def test_in_past(self):             ok("2020-01-01", "must be in the past"); fail("2099-01-01", "must be in the past")
    def test_in_future(self):           ok("2099-01-01", "must be in the future"); fail("2020-01-01", "must be in the future")


# ── Types / Structure ─────────────────────────────────────────────────────────

class TestTypes:
    def test_boolean(self):         ok(True, "must be a boolean"); fail(1, "must be a boolean")
    def test_list(self):            ok([1,2], "must be a list"); fail((1,2), "must be a list")
    def test_dict(self):            ok({"a":1}, "must be a dict"); fail([1], "must be a dict")
    def test_tuple(self):           ok((1,2), "must be a tuple"); fail([1,2], "must be a tuple")
    def test_set(self):             ok({1,2}, "must be a set"); fail([1,2], "must be a set")
    def test_none(self):            ok(None, "must be none"); fail(0, "must be none")
    def test_not_none(self):        ok(1, "must not be none"); fail(None, "must not be none")
    def test_truthy(self):          ok(1, "must be truthy"); fail(0, "must be truthy")
    def test_falsy(self):           ok(0, "must be falsy"); fail(1, "must be falsy")
    def test_non_empty_list(self):  ok([1], "must be a non-empty list"); fail([], "must be a non-empty list")
    def test_non_empty_dict(self):  ok({"a":1}, "must be a non-empty dict"); fail({}, "must be a non-empty dict")
    def test_unique(self):          ok([1,2,3], "must have unique items"); fail([1,1,2], "must have unique items")
    def test_sorted(self):          ok([1,2,3], "must be a sorted list"); fail([3,1,2], "must be a sorted list")
    def test_has_key(self):         ok({"name":"Alice"}, "must contain the key 'name'"); fail({}, "must contain the key 'name'")
    def test_min_items(self):       ok([1,2,3], "must have at least 3 items"); fail([1,2], "must have at least 3 items")
    def test_max_items(self):       ok([1,2], "must have at most 3 items"); fail([1,2,3,4], "must have at most 3 items")
    def test_matrix(self):          ok([[1,2],[3,4]], "must be a matrix"); fail([1,2,3], "must be a matrix")
    def test_ascending(self):       ok([1,2,3], "must be in ascending order"); fail([3,2,1], "must be in ascending order")
    def test_descending(self):      ok([3,2,1], "must be in descending order"); fail([1,2,3], "must be in descending order")
    def test_contiguous(self):      ok([2,3,4,5], "must be a contiguous range"); fail([1,3,5], "must be a contiguous range")
    def test_list_of_ints(self):    ok([1,2,3], "must be a list of integers"); fail([1,"x"], "must be a list of integers")
    def test_list_of_strings(self): ok(["a","b"], "must be a list of strings"); fail(["a",1], "must be a list of strings")
    def test_sum_equals(self):      ok([1,2,3], "must have sum of 6"); fail([1,2,3], "must have sum of 7")
    def test_no_nulls(self):        ok([1,2,3], "must have no null values"); fail([1,None,3], "must have no null values")
    def test_json_serializable(self): ok({"a":[1,2]}, "must be json-serializable"); fail({"fn": lambda:None}, "must be json-serializable")
